M48
; DRILL file {KiCad 8.0.5} date 2025-01-03T15:42:33+0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-03T15:42:33+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.1742Y-4.8366
X6.3711Y-4.8366
T2
X3.3268Y-2.689
X3.3268Y-4.7795
X6.8898Y-2.689
X6.8898Y-4.7795
M30
